FROM golang:1.17-stretch

ENV CGO_ENABLED=0 \
    GO111MODULE=on \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

# Setup air hot reloader
RUN wget https://raw.githubusercontent.com/cosmtrek/air/master/install.sh && \
    chmod +x install.sh && \
    sh install.sh && \
    cp ./bin/air /bin/air && \
    rm -rf ./bin install.sh

# Symlink cli
RUN ln -s /app/cmd/worker/tmp/cli /usr/local/bin/cli

# Worker App does not expose ports

CMD [ "air", "-c", "./cmd/worker/air.toml" ]
