DROP INDEX CONCURRENTLY IF EXISTS "post_thread_id_idx";
DROP INDEX CONCURRENTLY IF EXISTS "post_creator_id_idx";
DROP INDEX CONCURRENTLY IF EXISTS "post_type_idx";
DROP INDEX CONCURRENTLY IF EXISTS "post_priority_idx";
DROP INDEX CONCURRENTLY IF EXISTS "post_recipient_ids_idx";
DROP INDEX CONCURRENTLY IF EXISTS "post_created_at_idx";
DROP TABLE IF EXISTS "post";
